# Generated by Django 5.2.3 on 2025-11-08 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.client'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='requirement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
