# Generated by Django 5.2.3 on 2025-11-11 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_lead_address_alter_lead_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('Referrals', 'Referrals'), ('E-mail', 'E-mail'), ('Advertisements', 'Advertisements'), ('Website', 'Website'), ('JD', 'JD'), ('Social media', 'Social media')], default='Referrals', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_person',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='mobile',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='requirement',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
