# Generated by Django 5.2.3 on 2025-09-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationitem',
            name='hsn_sac',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
