# Generated by Django 5.2.3 on 2025-10-21 13:51

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_estimationitem_hsn_sac'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultTerms',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='estimation',
        ),
        migrations.RenameField(
            model_name='gstsettings',
            old_name='percentage',
            new_name='gst_percentage',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='due_date',
            new_name='payment_date',
        ),
        migrations.RemoveField(
            model_name='termsandconditions',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='estimation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='estimationsettings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gstsettings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='utr_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='title',
            field=models.CharField(default='Default Terms', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estimation',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Lost', 'Lost'), ('Invoiced', 'Invoiced')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='validity_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partial Paid', 'Partial Paid'), ('Paid', 'Paid'), ('Pending', 'Pending')], default='Unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='computed_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='requirement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Quoted', 'Quoted'), ('Won', 'Won'), ('Lost', 'Lost'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
    ]
