# Generated by Django 5.2.3 on 2026-01-09 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_lead_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_no', models.CharField(max_length=50, unique=True)),
                ('dc_date', models.DateField()),
                ('delivery_address', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('terms', models.CharField(default='ABC', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.estimation')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('dc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.deliverychallan')),
                ('estimation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.estimationitem')),
            ],
        ),
    ]
