# Generated by Django 5.2.3 on 2025-10-22 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_delete_defaultterms_remove_quotationitem_estimation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userpermission',
            options={'ordering': ['name'], 'verbose_name': 'User Permission', 'verbose_name_plural': 'User Permissions'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='userpermission',
            name='code',
            field=models.CharField(default='crm.unknown', help_text="Stable code, e.g., 'crm.view_client'", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], db_index=True, default='User', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='name',
            field=models.CharField(help_text="Human label, e.g., 'crm | Can view client'", max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, help_text='Display name', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='crm.userpermission'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], db_index=True, default='User', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
