# Generated by Django 5.2.3 on 2026-01-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_invoice_invoice_no_deliverychallan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallanitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
