# Generated by Django 5.2.3 on 2026-01-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_deliverychallanitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverychallanitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='estimationitem',
            name='hsn_sac',
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='uom',
            field=models.CharField(choices=[('Nos', 'Nos'), ('Box', 'Box'), ('Meter', 'Meter')], default='Nos', max_length=10),
        ),
    ]
