# Generated by Django 5.2.3 on 2026-01-12 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_deliverychallanitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='po_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='estimation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_challans', to='crm.estimation'),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='terms',
            field=models.TextField(default='Received the above mentioned goods in good condition, complaints (if any) contact within 24 hours'),
        ),
    ]
