# Generated by Django 5.2.3 on 2026-01-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_deliverychallan_po_date_deliverychallan_po_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationitem',
            name='hsn_sac',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
