# Generated by Django 5.2.3 on 2026-01-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_estimationitem_hsn_sac'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationitem',
            name='uom',
            field=models.CharField(choices=[('Nos', 'Nos'), ('Box', 'Box'), ('Meter', 'Meter')], default='Nos', max_length=10),
        ),
    ]
