# Generated by Django 5.2.3 on 2025-11-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_user_mobile_alter_user_role_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpermission',
            options={'verbose_name': 'User Permission', 'verbose_name_plural': 'User Permissions'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='userpermission',
            name='codename',
            field=models.CharField(default='', help_text="Codename must match Django's built-in permission codename (e.g., 'add_client').", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
