# Generated by Django 5.2.3 on 2026-02-05 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_estimationitem_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('old_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='crm.invoice')),
            ],
        ),
    ]
