# Generated by Django 5.2.3 on 2025-11-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_userpermission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='codename',
            field=models.CharField(blank=True, help_text='Temporary nullable codename (will fill and re-enforce uniqueness later)', max_length=100, null=True),
        ),
    ]
