# Generated by Django 5.2.3 on 2026-02-19 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_calllog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='call_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
