# Generated by Django 5.2.3 on 2026-02-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_calllog_call_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='lead',
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_type',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('missed', 'Missed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('follow_up', 'Follow Up'), ('junk', 'Junk'), ('lead_stage', 'Lead Stage'), ('existing_client', 'Existing Client'), ('missed', 'Missed')], max_length=30),
        ),
    ]
