# Generated by Django 5.2.3 on 2026-02-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_remove_calllog_assigned_to_remove_calllog_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='call_type',
            field=models.CharField(choices=[('incoming', 'Picked Up Call'), ('missed', 'Missed Call')], max_length=20),
        ),
    ]
