# Generated by Django 5.2.3 on 2026-02-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_calllog_call_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='call_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
