# Generated by Django 5.2.3 on 2026-02-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_calllog_call_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calllog',
            options={'ordering': ['-call_time']},
        ),
        migrations.AddField(
            model_name='calllog',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_type',
            field=models.CharField(choices=[('incoming', 'Picked Up Call'), ('missed', 'Missed Call')], default='incoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('follow_up', 'Follow Up'), ('junk', 'Junk'), ('lead_stage', 'Lead Stage'), ('existing_client', 'Existing Client'), ('missed', 'Missed')], default='follow_up', max_length=30),
        ),
    ]
