# Generated by Django 5.2.3 on 2026-02-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_alter_calllog_options_calllog_remarks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calllog',
            options={},
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='email',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='location',
        ),
        migrations.AddField(
            model_name='calllog',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_type',
            field=models.CharField(choices=[('incoming', 'Picked Up Call'), ('missed', 'Missed Call')], max_length=20),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('follow_up', 'Follow Up'), ('junk', 'Junk'), ('lead_stage', 'Lead Stage'), ('existing_client', 'Existing Client'), ('missed', 'Missed')], max_length=30),
        ),
    ]
