# Generated by Django 5.2.3 on 2026-02-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_alter_calllog_options_remove_calllog_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
