# Generated by Django 5.2.3 on 2026-02-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_calllog_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='sim_slot',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
