# Generated by Django 5.2.3 on 2026-02-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_calllog_sim_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='call_type',
            field=models.CharField(choices=[('picked', 'Picked Up Call'), ('outgoing', 'Out Going Call'), ('missed', 'Missed Call')], max_length=20),
        ),
    ]
